# Generated by Django 4.0.4 on 2022-05-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
