# Generated by Django 4.0.4 on 2022-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_newsitem_image_alter_newsitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('news', models.ManyToManyField(to='app.newsitem')),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
    ]
